<?php //$Id$

/**
 * @file
 * The Webform MySQL Views module allows you to automatically build flattened
 * MySQL views of submitted Webform module data, for convenient use by external
 * applications.
 */

/**
 * Implementation of hook_menu().
 */
function webform_mysql_views_menu() {
  $items = array();

  // Submissions listing.
  $items['admin/content/webform/webform'] = array(
    'title' => 'Webforms',
    'page callback' => 'webform_admin_content',
    'access callback' => 'user_access',
    'access arguments' => array('access all webform results'),
    'description' => 'View and edit all the available webforms on your site.',
    'file' => 'includes/webform.admin.inc',
    'file path' => drupal_get_path('module', 'webform'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 0,
  );

  // MySQL Views settings
  $items['admin/content/webform/mysql'] = array(
    'title' => 'MySQL Views',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('webform_mysql_views_admin_form'),
    'access callback' => 'user_access',
    'access arguments' => array('access all webform results'),
    'description' => 'Create MySQL views of submitted Webform data.',
    'file' => 'includes/webform_mysql_views.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 2,
  );

  return $items;
}

/**
 * Implementation of hook_help().
 */
//function webform_mysql_views_help($path) {
//  switch($path) {
//    case 'admin/content/webform/mysql':
//
//  }
//}

/**
 * Given a webform node ID, build an SQL query that will create a flat MySQL view
 * of subnissions for that webform
 */
function webform_mysql_views_build_query($nid, $view_name) {
  $query = db_result(
    db_query("SELECT CONCAT(
      \"CREATE OR REPLACE VIEW %s AS SELECT parent.sid, webform_submissions.uid, \",
      GROUP_CONCAT(
        CONCAT(\"(SELECT data FROM webform_submitted_data AS child WHERE child.sid = parent.sid AND cid = \", c.cid, \") AS \", c.form_key)
      ),
      \", FROM_UNIXTIME(webform_submissions.submitted) AS submitted, webform_submissions.remote_addr FROM webform_submitted_data AS parent JOIN webform_submissions ON webform_submissions.sid = parent.sid WHERE parent.nid = %d GROUP BY parent.sid ORDER BY parent.sid DESC;\"
    ) AS query
    FROM webform_component c
    WHERE c.nid = %d", $view_name, $nid, $nid)
  );
  return $query;
}

/**
 * Get a unique view name from a given string and node ID.
 */
function webform_mysql_views_get_view_name($title, $nid) {
  //Discard non-alphanumeric chars
  $title = strtolower(str_replace(' ', '_', $title));
  $title = 'webform_views_' .preg_replace('/[^a-z0-9_]/', '', $title);

  /* Check whether the default view name is already being used
   * (For example duplicate node titles). Append $nid if necessary to ensure
   * uniqueness
   */
  $view_exists = db_result(db_query("SELECT COUNT(table_name) AS view_exists FROM information_schema.tables where table_schema = 'drupal6_rcapp_dev' AND table_name = '%s'", $title));

  if ($view_exists) {
    return $title. '_' .$nid;
  }

  return $title;
}